lifesteal = {}

[curse_breaking]
	enable = true

[curse_butterfingers]
	enable = true

[curse_aquaphobia]
	enable = true

[curse_death]
	enable = true

[reinforced_tip]
	enable = true

[stone_mending]
	enable = true

[lumberjack]
	enable = false

[momentum]
	enable = true

[butchering]
	enable = true

[true_shot]
	enable = true

[quick_draw]
	enable = true

[floating]
	enable = true

[paralysis]
	enable = true

[detonation]
	enable = true

[combo]
	enable = true

[faster_attack]
	enable = true

